from __future__ import annotations
from collections import defaultdict
from datetime import datetime, date
from pathlib import Path

from tools.kb.core.entry import scan_entries
from tools.kb.core.atomic import write_text_atomic


def _make_index(path: Path, title: str, groups: dict) -> None:
    lines = [
        "<!-- AUTO-GENERATED by tools/kb. DO NOT EDIT. -->\n",
        f"# KB Index by {title}\n",
    ]
    for key in sorted(groups):
        lines.append(f"\n## {key}\n")
        for e in sorted(groups[key], key=lambda x: x.id):
            rel = e.path.relative_to(path.parent.parent)
            lines.append(f"- [`{e.id}`]({rel}) — {e.claim}\n")

    write_text_atomic(path, "".join(lines))


def cmd_gen_indexes_main(root: Path, args) -> int:
    entries = [e for e in scan_entries(root) if e.status == "current"]

    # By cluster
    by_cluster: dict[str, list] = defaultdict(list)
    for e in entries:
        by_cluster[e.cluster or "unknown"].append(e)
    _make_index(root / "INDEX-by-cluster.md", "Cluster", dict(by_cluster))

    # By tag
    by_tag: dict[str, list] = defaultdict(list)
    for e in entries:
        for tag in e.tags:
            by_tag[f"#{tag}"].append(e)
    _make_index(root / "INDEX-by-tag.md", "Tag", dict(by_tag))

    # By module
    by_module: dict[str, list] = defaultdict(list)
    for e in entries:
        for mod in e.modules:
            by_module[mod].append(e)
    _make_index(root / "INDEX-by-module.md", "Module", dict(by_module))

    # By kind
    by_kind: dict[str, list] = defaultdict(list)
    for e in entries:
        by_kind[e.kind or "unknown"].append(e)
    _make_index(root / "INDEX-by-kind.md", "Kind", dict(by_kind))

    # Stale
    today = date.today()
    stale_lines = [
        "<!-- AUTO-GENERATED by tools/kb. DO NOT EDIT. -->\n",
        "# KB Stale Entries\n",
        f"\n超期阈值: 全局 6 月 / per-entry verify_freq 覆盖\n",
    ]
    for e in entries:
        if not e.verified:
            continue
        try:
            vd = datetime.strptime(e.verified, "%Y-%m-%d").date()
        except ValueError:
            continue
        months_map = {"monthly": 1.5, "quarterly": 4, "yearly": 13}
        threshold = months_map.get(e.verify_freq, 6) if e.verify_freq else 6
        delta = (today - vd).days / 30
        if delta > threshold:
            rel = e.path.relative_to(root.parent.parent)
            stale_lines.append(f"- [`{e.id}`]({rel}) ({int(delta)} 月前) — {e.claim}\n")

    write_text_atomic(root / "INDEX-stale.md", "".join(stale_lines))

    print("INDEX-*.md 已重新生成")
    return 0
